### ISSUE TITLE
Incorrect Craft Version 

### ISSUE THREAD

**Issue by baileydoestech** [Firstborn/Craft-Migration-Manager#1]
Hi, when running Craft Pro it looks like you haven't updated your code to handle the new Craft license model when accessing the plugin from the CP:

![image](https://user-images.githubusercontent.com/3185073/39052206-2b630252-44a3-11e8-9371-a1a4b9522466.png)

![image](https://user-images.githubusercontent.com/3185073/39052254-53140f9e-44a3-11e8-939f-eb9cf6a96a09.png)

**Comment by theskyfloor** [comment]
I'm getting this same error on Solo

**Comment by fb-derrick-grigg** [comment]
@lukebailey  @theskyfloor thanks for catching that.
