### ISSUE TITLE
Installing manually does not result in the plugin appearing on the Plugins pane

### ISSUE THREAD

**Issue by gregorskii** [Firstborn/Craft-Migration-Manager#12]
Following the readme:

https://github.com/Firstborn/Craft-Migration-Manager#composer-command-line-the-manual-way

Results in the plugin not showing in the Plugins pane of the CMS.

Using Craft Pro 3.0.6.

I am currently overriding the location of this plugin in composer to use my fork:

```
"repositories": [
    {
      "type":"package",
      "package": {
        "name": "firstborn/migrationmanager",
        "version":"3.0.7",
        "source": {
          "url": "https://github.com/gregorskii/Craft-Migration-Manager.git",
          "type": "git",
          "reference":"feature/fix-disabled-backup"
        }
      }
    }
  ],
```

On plugins after a completely fresh install the plugin is not present in the Plugins pane:

![screenshot 2018-05-09 17 03 59](https://user-images.githubusercontent.com/1130448/39845483-feed8bcc-53aa-11e8-865e-a2937a1fd874.png)

**Comment by gregorskii** [comment]
Tested it without the repo override, it does register. May be an odd quirk of composer? When using the repo / package lines above the correct forked code does appear in vendor, but the plugin does not appear in the admin panel.

**Comment by fb-derrick-grigg** [comment]
Try running:
composer dump-autoload 
composer update

**Comment by gregorskii** [comment]
I am using docker with volumes, the composer install command runs inside of the container, thus there is no composer cache or files to dump. On each test I was destroying any volumes I had.

**Comment by fb-derrick-grigg** [comment]
I'm not sure about the docker side of things. When you run the 'composer require firstborn/migrationmanager' command that should update the 'vendor/craftcms/plugins.php' file. If that is not updating, try this https://craftcms.stackexchange.com/questions/21479/craft-3-forgets-plugins/21497

**Comment by gregorskii** [comment]
Ok will look into this. I think its composer related / my knowledge of using custom forks for repos.

I don't think it has anything to do with your plugin.

Thanks

**Comment by webdevotion** [comment]
To install the plugin without using the Control panel you can run 
`./craft install/plugin migrationmanager`
after the `require` step as per README.
