### ISSUE TITLE
array_key_exists() expects parameter 2 to be array, null given

### ISSUE THREAD

**Issue by retop** [Firstborn/Craft-Migration-Manager#13]
Thanks for this plugin!
Migration to freshly installed Craft CMS fails with the following error message:
```
A fatal error has occurred:
Status: Internal Server Error
Response: {"error":"An error occurred while executing the \"craft\\contentmigrations\\m180514_155140_migration_everything migration: array_key_exists() expects parameter 2 to be array, null given"}
```
 no further explanation found in logs - any hints what to do to get this working? 
Thanks!

**Comment by fb-derrick-grigg** [comment]
Do you have dev mode enabled in your Craft site? What are you trying to create a migration for?

**Comment by retop** [comment]
Hey  fb-derrick-grigg , thanks!
Yes, dev mode is enabled - i see no errors in the logs though...
I try to migrate basically everything: all the fields, sections, categories and so on.

All i find in the logs is: 
```
2018-05-14 07:11:54 [217.110.40.37][1][-][error][craft\errors\MigrationException] yii\base\ErrorException: array_key_exists() expects parameter 2 to be array, null given in /html/Craft-Staging-2/vendor/firstborn/migrationmanager/src/services/Migrations.php:244
```
and
```
Next craft\errors\MigrationException: An error occurred while executing the "craft\contentmigrations\m180514_155140_migration_maybeEverything migration: array_key_exists() expects parameter 2 to be array, null given in /html/Craft-Staging-2/vendor/craftcms/cms/src/db/MigrationManager.php:260
```
Any idea how to proceed?
thanks!

**Comment by fb-derrick-grigg** [comment]
Are you on version 3.0.8? 

Do you have any AssetVolumes? Try doing an export without them.

**Comment by fb-derrick-grigg** [comment]
Also, can you attach a copy of your migration file?

**Comment by fb-derrick-grigg** [comment]
@retop I think it might be the actual JSON data that is in the migration file. Can you attach a copy of your migration file? Also, try migrating smaller sets of data, instead of everything.

**Comment by gregorskii** [comment]
Confirming I also get this. The value being passed to the migration $json is set, it gets lost inside of this plugin.

Oddly... if I import the json from a file and use a bit of code in the migration file it does not fail for me. Its also intermittent with the $json string value...

Rather than:

```
$json = '{JSON STRING}'

        return MigrationManager::getInstance()->migrations->import($json);
```

I use:

```
$cwd = getcwd();
        
        # Path to migrations is different when running ./craft on CLI and from web admin
        if (strpos($cwd, 'web') !== false) {
            $json = file_get_contents('../migrations/data.json');
        } else {
            $json = file_get_contents('./migrations/data.json');
        }
        return MigrationManager::getInstance()->migrations->import($json);
```

Where `data.json` is the same thing as whats in the string $json just as an actual json file.

**Comment by fb-derrick-grigg** [comment]
It's likely a problem character in the JSON string when it gets decoded. Can you attach a sample of a migration that fails for you?

When PHP attempts to convert JSON into an array it likes to fail silently.

**Comment by gregorskii** [comment]
Mine are for a private app for a client. I am certain the JSON is correct inside. To create the above JSON files all I did was format the single line and save it as a JSON file. I have also ran mine through JSON lint.

**Comment by fb-derrick-grigg** [comment]
What did you do to format the JSON string?

**Comment by gregorskii** [comment]
Took the string from ```$json = '{JSON_STRING}'```, and put `{JSON_STRING}` in VSCode, then ran a JSON formatter. Took that result, saved it to the file `data.json` and also took the resulting string to a JSON validator.

**Comment by fb-derrick-grigg** [comment]
Just curious, if you compare the actual JSON string before and after the formatter is there a difference?

**Comment by gregorskii** [comment]
Nope, I don't think so. I have been using the same JSON formatters for ages, never had one correct JSON for me. Besides the $json in the string was generated by the plugin in the admin panel.

**Comment by fb-derrick-grigg** [comment]
@gregorskii @retop do you know if there are any odd characters in the JSON string. It might be a character encoding issue.

**Comment by gregorskii** [comment]
No I don’t think so. It’s hard to tell, in order to take it out of the string form the migration is created in I have to save it to my editor, which could be changing the character encodings. But I honestly do not think so.

If the json was unparsable the plugin should indicate this rather than saying it’s empty, understandably that’s an enhancement. But currently it’s hard for me to diagnose if that is the issue.

**Comment by gregorskii** [comment]
Using the process I am using above seems more reliable, the JSON files it imports can be viewed as plain JSON and linted. Is there a technical reason (like Yii) that this plugin stores the JSON migration data as a string and not a CDATA or json file next to the migration script itself? Essentially its harder to track issues in the JSON if its a flat string than a easily copyable JSON string with newlines etc.

What do you think?

**Comment by fb-derrick-grigg** [comment]
@gregorskii @retop I have added some additional code to help with decoding the json and also some error logging to determine when and why a json error has happened.

**Comment by gregorskii** [comment]
Awesome thank you. 👍

**Comment by martisj** [comment]
I want to quickly second the question about CDATA or a separate JSON file. What is the reason JSON is output as a string?
What is the downside of using Herdoc, to the tune of something like this:

```php
$json = <<<JSON
{
  "content": {
    "entries": [
      {
        "slug": "appendix",
        "section": "articles",
        "locales": {
          "en_us": {
            "slug": "appendix",
            "section": "articles",
            "enabled": "1",
            "locale": "en_us",
            "localeEnabled": "1",
            "textField": "<a href=\u0022http://www.google.com\u0022>My link's to work</a>"
          }
        }
      }
    ]
  }
}
JSON;
```

**Comment by gregorskii** [comment]
A heredoc would work. I tried doing this and it did not work. I had the same result as if the json was a single line string.

I have found the most reliable option was to extract it to its own file, it never fails. 

Understood that that may not make sense... but it inconsistently fails for me keeping it in string form.

**Comment by fb-derrick-grigg** [comment]
I can investigate the heredoc idea. The reason for a single file was the way Craft reads and lists migration files from the migration directory.

**Comment by gregorskii** [comment]
Yep, makes sense. I had to add a switch to determine if it was running in CLI or web mode to read a json file.

It’s much more succinct to have it all in one file either way. It’s more consistent with other frameworks like laravel. Yii/Crafts migrations being flat json rather than code (like eloquent) makes it interesting as these migrations are parsed rather than processed by an api.

I think it makes sense to use heredocs for clarity (and ease of reading the migration) if that ends up working for most users my errors may be in the minority.

Thanks
