### ISSUE TITLE
Download migrations from remote server

### ISSUE THREAD

**Issue by gregorskii** [Firstborn/Craft-Migration-Manager#14]
Hello!

Another suggestion:

Currently this plugin creates migrations in the file system, if Craft is hosted on a transient file system like Docker there is no clear way to download the migration files. It would be great if this plugin created a migration file on the server, but also allowed you to download the migration JSON/php file via the CMS UI. You would then take this file and put it in your GIT repo to be stored for local dev / promotion to production.

Just a little more background... we do structure changes on local (Docker instances) and create field / section migration files to push to staging for validation on a remote server, we then migrate the code (including the local migrations to an authoring server where the team can author and preview content changes. We then would like to create content migration on the authoring server to promote the created content items to production.

Essentially the age old issue of migrating CMS content... ha

**Comment by dgrigg** [comment]
Closing this. Files are created in the file system and can be added to VCS as needed from the command line. Please refer to readme https://github.com/Firstborn/Craft-Migration-Manager
