### ISSUE TITLE
Asset field import fail

### ISSUE THREAD

**Issue by zyleee** [Firstborn/Craft-Migration-Manager#15]
Hi there

I am running into a problem with asset fields. 
If I import them and then want to create a new entry for that field I always get the message:
 `The Image field’s Default Upload Location setting is set to an invalid volume.`

Am I doing something wrong while exporting the fields?

Many thanks in advance

**Comment by fb-derrick-grigg** [comment]
@zyleee it sounds like you have migrated an asset field but not the corresponding asset volume to the destination site. Try migrating the asset volume first and then the field.

**Comment by zyleee** [comment]
Hi @fb-derrick-grigg 

That is already happening, the asset volume is migrated first and after that the field to make sure the volume exists. 

I can go to Settings > Fields and re-save the field after the migration, then it works. However, if there is a content migration right after the field migration, at this point the asset field is invalid and it won't migrate the content correctly.

Any idea on this?

Many thanks in advance.

**Comment by OscarBarrett** [comment]
Running into this also.

I have an S3 volume with the following config:

```json
{
    "name": "Assets",
    "handle": "assets",
    "type": "craft\\\\awss3\\\\Volume",
    "sortOrder": "1",
    "typesettings": {
        "subfolder": "",
        "keyId": "<key>",
        "secret": "<secret>",
        "bucket": "<bucket>",
        "region": "ap-southeast-2",
        "expires": "1 days",
        "storageClass": "",
        "cfDistributionId": ""
    },
    "hasUrls": 1,
    "url": "https://s3-ap-southeast-2.amazonaws.com/<bucket>/"
}
```

And several fields that allow single uploads to this asset source with a custom path.

When generating a migration that includes both the volume and field, `defaultUploadLocationSource` and `singleUploadLocationSource` are blank in the generated json.

e.g.
```json
{
    "group": "Common",
    "name": "Hero Image",
    "handle": "heroImage",
    "instructions": null,
    "translationMethod": "site",
    "translationKeyFormat": null,
    "required": null,
    "type": "craft\\\\fields\\\\Assets",
    "typesettings": {
        "useSingleFolder": true,
        "defaultUploadLocationSource": "",
        "defaultUploadLocationSubpath": "",
        "singleUploadLocationSource": "",
        "singleUploadLocationSubpath": "hero-images",
        "restrictFiles": true,
        "allowedKinds": ["image"],
        "sources": [],
        "source": null,
        "targetSiteId": null,
        "viewMode": "large",
        "limit": 1,
        "selectionLabel": "Add an image",
        "localizeRelations": false
    }
}
```

Right after migration, the field settings in the database are as follows, and trying to edit an entry that uses the field shows `The Hero Image field’s Upload Location setting is set to an invalid volume.`
```json
{
    "useSingleFolder": true,
    "defaultUploadLocationSource": "",
    "defaultUploadLocationSubpath": "",
    "singleUploadLocationSource": "",
    "singleUploadLocationSubpath": "hero-images",
    "restrictFiles": true,
    "allowedKinds": ["image"],
    "sources": "*",
    "source": null,
    "targetSiteId": null,
    "viewMode": "large",
    "limit": 1,
    "selectionLabel": "Add an image",
    "localizeRelations": false
}
```

If I go to the field settings in Craft and save it (making no changes), it updates to the following and the field works when editing an entry.
```json
{
    "useSingleFolder": "1",
    "defaultUploadLocationSource": "folder:1",
    "defaultUploadLocationSubpath": "",
    "singleUploadLocationSource": "folder:1",
    "singleUploadLocationSubpath": "hero-images",
    "restrictFiles": "1",
    "allowedKinds": ["image"],
    "sources": "*",
    "source": null,
    "targetSiteId": null,
    "viewMode": "large",
    "limit": "1",
    "selectionLabel": "Add an image",
    "localizeRelations": false
}
```

**Comment by fb-derrick-grigg** [comment]
@zyleee @OscarBarrett try the latest version
