### ISSUE TITLE
Migration Manager loading cpresources on front end

### ISSUE THREAD

**Issue by AndrewMac** [Firstborn/Craft-Migration-Manager#2]
Hello there, I installed Migration Manager recently, and then noticed layout issues on the front-end site that were caused by the site somehow loading a bunch of stylesheet files from the cpresources directory, immediately under my own CSS links.

These were:

`
link href="https://site.dev/cpresources/1f31763d/selectize.css?v=1524281801" rel="stylesheet"

link href="https://site.dev/cpresources/191e5374/css/craft.css?v=1524281800" rel="stylesheet"

link href="https://site.dev/cpresources/191e5374/css/charts.css?v=1524281800" rel="stylesheet"

link href="https://site.dev/cpresources/4770a90c/css/migration-manager-sidebar.css?v=1524281800" rel="stylesheet"
`

^ Sorry, had to take out the angle brackets to make it display.

Seeing the migration manager file caused me to disable the plug-in, and things went back to normal, with none of these extra stylesheet links showing up.

Is this something you can replicate or not? If not, do you have any idea why it might be happening?

Thanks in advance for any help or advice you may be able to give with this.

**Comment by fb-derrick-grigg** [comment]
fixed in latest release
