### ISSUE TITLE
Error while trying to migrate asset transforms

### ISSUE THREAD

**Issue by frontedbe** [Firstborn/Craft-Migration-Manager#20]
When trying to migrate asset transforms from one project to an empty project with no transforms, I get this error => [view image](https://cl.ly/soOM)

The JSON string is this =>

`{"settings":{"dependencies":{"assetTransforms":[{"name":"Extra Extra Large","handle":"xxl","width":"1920","height":"1920","format":null,"mode":"fit","position":"center-center","quality":"82","interlace":"none"},{"name":"Extra Extra Large — Landscape","handle":"xxlLandscape","width":"1920","height":"1280","format":null,"mode":"crop","position":"center-center","quality":"82","interlace":"none"},{"name":"Extra Extra Large — Portrait","handle":"xxlPortrait","width":"1280","height":"1920","format":null,"mode":"crop","position":"center-center","quality":"82","interlace":"none"},{"name":"Extra Large","handle":"xl","width":"1440","height":"1440","format":null,"mode":"fit","position":"center-center","quality":"82","interlace":"none"},{"name":"Extra Large — Landscape","handle":"xlLandscape","width":"1440","height":"993","format":null,"mode":"crop","position":"center-center","quality":"82","interlace":"none"},{"name":"Extra Large — Portrait","handle":"xlPortrait","width":"933","height":"1440","format":null,"mode":"crop","position":"center-center","quality":"82","interlace":"none"},{"name":"Extra small","handle":"xs","width":"480","height":"480","format":null,"mode":"fit","position":"center-center","quality":"82","interlace":"none"},{"name":"Extra Small — Landscape","handle":"xsLandscape","width":"480","height":"320","format":null,"mode":"crop","position":"center-center","quality":"82","interlace":"none"},{"name":"Extra Small — Portrait","handle":"xsPortrait","width":"320","height":"480","format":null,"mode":"crop","position":"center-center","quality":"82","interlace":"none"},{"name":"Large","handle":"lg","width":"1200","height":"1200","format":null,"mode":"fit","position":"center-center","quality":"82","interlace":"none"},{"name":"Large — Landscape","handle":"lgLandscape","width":"12800","height":"800","format":null,"mode":"crop","position":"center-center","quality":"82","interlace":"none"},{"name":"Large — Portrait","handle":"lgPortrait","width":"800","height":"1200","format":null,"mode":"crop","position":"center-center","quality":"82","interlace":"none"},{"name":"Medium","handle":"md","width":"960","height":"960","format":null,"mode":"fit","position":"center-center","quality":"82","interlace":"none"},{"name":"Medium Large","handle":"ml","width":"1024","height":"1024","format":null,"mode":"fit","position":"center-center","quality":"82","interlace":"none"},{"name":"Medium Large — Landscape","handle":"mlLandscape","width":"1024","height":"683","format":null,"mode":"crop","position":"center-center","quality":"82","interlace":"none"},{"name":"Medium Large — Portrait","handle":"mlPortrait","width":"683","height":"1024","format":null,"mode":"crop","position":"center-center","quality":"82","interlace":"none"},{"name":"Medium — Landscape","handle":"mdLandscape","width":"960","height":"640","format":null,"mode":"crop","position":"center-center","quality":"82","interlace":"none"},{"name":"Medium — Portrait","handle":"mdPortrait","width":"640","height":"960","format":null,"mode":"crop","position":"center-center","quality":"82","interlace":"none"},{"name":"Small","handle":"sm","width":"768","height":"768","format":null,"mode":"fit","position":"center-center","quality":"82","interlace":"none"},{"name":"Small video (16:9)","handle":"smVideo","width":"768","height":"432","format":null,"mode":"crop","position":"center-center","quality":"82","interlace":"none"},{"name":"Small — Landscape","handle":"smLandscape","width":"768","height":"512","format":null,"mode":"crop","position":"center-center","quality":"82","interlace":"none"},{"name":"Small — Portrait","handle":"smPortrait","width":"512","height":"768","format":null,"mode":"crop","position":"center-center","quality":"82","interlace":"none"}]},"elements":{"assetTransforms":[{"name":"Extra Extra Large","handle":"xxl","width":"1920","height":"1920","format":null,"mode":"fit","position":"center-center","quality":"82","interlace":"none"},{"name":"Extra Extra Large — Landscape","handle":"xxlLandscape","width":"1920","height":"1280","format":null,"mode":"crop","position":"center-center","quality":"82","interlace":"none"},{"name":"Extra Extra Large — Portrait","handle":"xxlPortrait","width":"1280","height":"1920","format":null,"mode":"crop","position":"center-center","quality":"82","interlace":"none"},{"name":"Extra Large","handle":"xl","width":"1440","height":"1440","format":null,"mode":"fit","position":"center-center","quality":"82","interlace":"none"},{"name":"Extra Large — Landscape","handle":"xlLandscape","width":"1440","height":"993","format":null,"mode":"crop","position":"center-center","quality":"82","interlace":"none"},{"name":"Extra Large — Portrait","handle":"xlPortrait","width":"933","height":"1440","format":null,"mode":"crop","position":"center-center","quality":"82","interlace":"none"},{"name":"Extra small","handle":"xs","width":"480","height":"480","format":null,"mode":"fit","position":"center-center","quality":"82","interlace":"none"},{"name":"Extra Small — Landscape","handle":"xsLandscape","width":"480","height":"320","format":null,"mode":"crop","position":"center-center","quality":"82","interlace":"none"},{"name":"Extra Small — Portrait","handle":"xsPortrait","width":"320","height":"480","format":null,"mode":"crop","position":"center-center","quality":"82","interlace":"none"},{"name":"Large","handle":"lg","width":"1200","height":"1200","format":null,"mode":"fit","position":"center-center","quality":"82","interlace":"none"},{"name":"Large — Landscape","handle":"lgLandscape","width":"12800","height":"800","format":null,"mode":"crop","position":"center-center","quality":"82","interlace":"none"},{"name":"Large — Portrait","handle":"lgPortrait","width":"800","height":"1200","format":null,"mode":"crop","position":"center-center","quality":"82","interlace":"none"},{"name":"Medium","handle":"md","width":"960","height":"960","format":null,"mode":"fit","position":"center-center","quality":"82","interlace":"none"},{"name":"Medium Large","handle":"ml","width":"1024","height":"1024","format":null,"mode":"fit","position":"center-center","quality":"82","interlace":"none"},{"name":"Medium Large — Landscape","handle":"mlLandscape","width":"1024","height":"683","format":null,"mode":"crop","position":"center-center","quality":"82","interlace":"none"},{"name":"Medium Large — Portrait","handle":"mlPortrait","width":"683","height":"1024","format":null,"mode":"crop","position":"center-center","quality":"82","interlace":"none"},{"name":"Medium — Landscape","handle":"mdLandscape","width":"960","height":"640","format":null,"mode":"crop","position":"center-center","quality":"82","interlace":"none"},{"name":"Medium — Portrait","handle":"mdPortrait","width":"640","height":"960","format":null,"mode":"crop","position":"center-center","quality":"82","interlace":"none"},{"name":"Small","handle":"sm","width":"768","height":"768","format":null,"mode":"fit","position":"center-center","quality":"82","interlace":"none"},{"name":"Small video (16:9)","handle":"smVideo","width":"768","height":"432","format":null,"mode":"crop","position":"center-center","quality":"82","interlace":"none"},{"name":"Small — Landscape","handle":"smLandscape","width":"768","height":"512","format":null,"mode":"crop","position":"center-center","quality":"82","interlace":"none"},{"name":"Small — Portrait","handle":"smPortrait","width":"512","height":"768","format":null,"mode":"crop","position":"center-center","quality":"82","interlace":"none"}]}}}`

**Comment by dgrigg** [comment]
this has been fixed, you will need to create a new asset transform migration.
