### ISSUE TITLE
User/group permissions "Create Migration"

### ISSUE THREAD

**Issue by jeroenlammerts** [Firstborn/Craft-Migration-Manager#23]
```
"craftcms/cms": "3.0.16",
"firstborn/migrationmanager": "v3.0.11"
```

When checkbox "Access Migration Manager" is unchecked, users are still able to see and use the function to create an content migration. For example: /admin/entries, select an item, then you have the function "Create Migration".

I think this can be checked something like `$user->can('accessMigrationManager')`

**Comment by fb-derrick-grigg** [comment]
@jeroenlammerts this was intentional, content editors don't have access to run migrations or creating migrations for settings etc, however for content migrations I felt it was good to allow them, as they know when content is getting update.

**Comment by jeroenlammerts** [comment]
@fb-derrick-grigg it would be nice to disable this setting, when you not need it, to keep the interface as clean as possible.
It also needs a workflow with git when migrations are made on a staging/production environment.

**Comment by fb-derrick-grigg** [comment]
@jeroenlammerts that would be an option that would make sense. Regarding the work flow I would suggest using a similar source control workflow to however you currently manage updates. It would require committing code from your stage/prod. Managing/integrating with source control is outside the scope of this plugin.

**Comment by dgrigg** [comment]
Added a 'Create Content Migrations' permission for non admin users. Admins always have full migrations rights.
