### ISSUE TITLE
Matrix content erased nested SuperTable/Matrix

### ISSUE THREAD

**Issue by jeroenlammerts** [Firstborn/Craft-Migration-Manager#24]
```
"craftcms/cms": "3.0.16",
"firstborn/migrationmanager": "v3.0.11"
```

I have the following setup for content blocks in Craft:

Matrix (contentBlocks) > Block (ctaWithImages) > Field (buttonLink) > SuperTable Row Layout Static > Field (item) > Matrix with 2 fields

I know this pushing to the limits of field structures in Craft but if I create an migration for this setup and run it, the deepest Matrix field is erased after the migration is complete.

If I check the database the table matrixcontent_item is empty.

This could also be related to an issue with SuperTable: https://github.com/verbb/super-table/issues/145

**Comment by dgrigg** [comment]
Tested and this is working fine. The SuperTable issue was likely the cause.

**Comment by roelvanhintum** [comment]
That exact same setup (field handles are different) is causing the same problem for me. I'm using 2 sites in one group for multiple languages.

Field is like:
- modules (Matrix)
  - text (MatrixBlock)
    - aside (SuperTable static)
      - asideModule (Matrix)
        - asideText (MatrixBlock)
          - asideTitle (PlainText)
          - body (Redactor)
        - asideOther (MatrixBlock)
        - etc
  - other (MatrixBlock)
  - etc


I'm using:
- Craft CMS 3.1.15
- Migration Manager 3.0.19
- Super Table 2.1.13.1

**Comment by dgrigg** [comment]
@jeroenlammerts this issue just came up again and has been fixed, in the case it was still an issue for you.
