### ISSUE TITLE
Problem with character encoding

### ISSUE THREAD

**Issue by urbantrout** [Firstborn/Craft-Migration-Manager#26]
There seems to be a problem when applying a migration which contains special characters like German Umlauts. The attached gist contains a migrations with some **ä** characters. They are fine until this line of code is executed: https://github.com/Firstborn/Craft-Migration-Manager/blob/master/src/services/Migrations.php#L236

https://gist.github.com/urbantrout/2f866c25fd6687ec16734307da0c23d2

**Comment by urbantrout** [comment]
More Details: 

craftcms/cms@3.0.18
firstborn/migrationmanager@3.0.11

**Comment by urbantrout** [comment]
I created a pull request #28

**Comment by henrikgundersen** [comment]
Works perfectly fine - fixes problems with Norwegian `æ`, `ø` and `å` characters

**Comment by anderthalb** [comment]
Hey, any ideas when this will be added to a new version?

**Comment by urbantrout** [comment]
In the meantime you can install my forked version via composer:

```
composer config repositories.firstborn/migrationmanager '{"type": "vcs", "url": "'https://github.com:urbantrout/Craft-Migration-Manager.git'", "no-api": true }'
composer require firstborn/migrationmanager:dev-master
```

**Comment by fb-ziad-hilal** [comment]
Thanks for doing this and sorry it took so long, I've gone ahead and merged this.

**Comment by AlexandreKilian** [comment]
is this already in a release? in 3.0.11, I am still getting encoding errors… the latest release is over 2 months old

**Comment by anderthalb** [comment]
Just to push this a tiny bit ... I would really appreciate a fresh version soon, too :-)

**Comment by fb-ziad-hilal** [comment]
Is it just the version number that needs to be updated?

**Comment by AlexandreKilian** [comment]
the version number, and it needs to be pushed to packagist…
by the way, the fix worked, I just imported a migration that was exported with the broken encoding
