### ISSUE TITLE
Deprecation error in services/BaseContentMigration.php

### ISSUE THREAD

**Issue by monachilada** [Firstborn/Craft-Migration-Manager#29]
![screen shot 2018-08-09 at 10 10 42](https://user-images.githubusercontent.com/613183/43886769-17fbaa72-9bbd-11e8-9bce-d45734901c3b.png)

**Comment by elfacht** [comment]
I got another one.

![migration-manager-deprecated](https://user-images.githubusercontent.com/529443/45074355-6bf3ba80-b0e3-11e8-83bb-3bc370d5b90a.JPG)

**Comment by adampatpattison** [comment]
Me too:
![image](https://user-images.githubusercontent.com/4398922/46282951-df65dc00-c56a-11e8-82b8-41b86ca669ac.png)
