### ISSUE TITLE
Packagist not hosting the latest version 3.0.12

### ISSUE THREAD

**Issue by adampatpattison** [Firstborn/Craft-Migration-Manager#33]
Hi, 

Thanks for the recent update.

![image](https://user-images.githubusercontent.com/4398922/46282718-2d2e1480-c56a-11e8-826d-66fffbf11f51.png)

I've managed to install it via the CraftCMS admin console but I update on my live and staging server via composer. However, the version 3.0.12 is not available on [packagist.org](https://packagist.org/packages/firstborn/migrationmanager) 

I am currently getting the following error:
`The requested package firstborn/migrationmanager 3.0.12 exists as firstborn/migrationmanager[3.0.0, 3.0.1, 3.0.10, 3.0.11, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.0.7, 3.0.8, 3.0.9, dev-develop, dev-master] but these are rejected by your constraint.`

Could you please look to update packagist. 

Thanks in advance.

**Comment by adampatpattison** [comment]
Ignore me! Sorry! My composer file got foobarred and set it to require 3.0.12 when you're not even there! 🙈 

My apologies for wasting your time.

**Comment by fb-ziad-hilal** [comment]
Hi @adampatpattison 

Someone else had created the Packagist page for this plugin, so I'm not sure how to update it there. Would you happen to know how? (We're not the account owner of that page)

**Comment by adampatpattison** [comment]
Hi @fb-ziad-hilal,

Oh right?! No, I'm not sure. I've only ever linked to my own accounts and when the github updates with tags it pulls it through automatically.

The user on packagist is: https://packagist.org/users/pinfirestudios/, I've followed my nose with them and found https://github.com/pinfirestudios which leads to a url http://www.pinfirestudios.com/ which redirects to https://www.justin-c.com/ which has some contact details on it. 

Email
justin@justin-c.com
LinkedIn
http://www.linkedin.com/pub/justin-cherniak/27/186/b69
Facebook
http://www.facebook.com/justin.cherniak
Skype
justin.cherniak
Github
https://github.com/jcherniak
https://github.com/pinfirestudios/
@pinfirestudios
@jcherniak

I would recommend contacting him and asking him to either manually update the package and/or give you and/or your team access to the vendor on packagist.

Hope this helps.

**Comment by fb-ziad-hilal** [comment]
Thanks Adam! I'll figure it out

**Comment by jcherniak** [comment]
Sorry for the delay in responding to this issue and your email, I've been traveling overseas with limited connectivity.

I cannot see a way to transfer the package from the packagist UI, but I opened a ticket there to get this moved: https://github.com/composer/packagist/issues/961

**Comment by fb-ziad-hilal** [comment]
Thank you!

**Comment by jcherniak** [comment]
Until I get some assistance from Packagist, I also manually updated the package, which resolves the immediate issue at hand.

**Comment by fb-ziad-hilal** [comment]
Hi @jcherniak, 

Thank you for doing that :)

It looks like Packagist replied:

> you can add him as maintainer (in the right column of the package view, there is a big + button near the list of maintainers) to give him access to the package on Packagist.
> 
> And then, after that, he can remove you from the list of maintainers if needed (I'm not sure it is possible to remove yourselves from the list, but you may even try it).

**Comment by roelvanhintum** [comment]
There are some releases missing, but the tags are correct (accept 3.0.12 is missing a "v").
Also the version number hasn't changed for the latest release: https://github.com/Firstborn/Craft-Migration-Manager/blob/master/composer.json#L4
