### ISSUE TITLE
Viability of mass content migrations

### ISSUE THREAD

**Issue by iparr** [Firstborn/Craft-Migration-Manager#34]
(Hello, thanks for the plugin!)

I'm developing a reasonably complex Craft website that uses one install to serve content to two domains.

Because of this, I have some entry structures with 1,000s of entries. I want to create a migration of content from one to the other.

This seems very difficult because I have to slowly load almost endless pages of entries and keep hitting that checkbox and then 'Create migration'.

Is there a better way to do this? Am I looking in the wrong place with this plugin?

Any suggestions appreciated!

**Comment by dgrigg** [comment]
Hi @iparr. For that many entries you might be better off trying something like the FeedMe plugin https://verbb.io/craft-plugins/feed-me/features

**Comment by iparr** [comment]
Thank you @dgrigg. I'm familiar with that useful plugin. I'm happy with the importing bit, but I'd need to generate my own custom feed for later consumption by FeedMe. Maybe I should look at [ElementAPI](https://github.com/craftcms/element-api). I wonder how much configuration is required to produce a bullet-proof feed that will be consumed effectively.

I guess I might just be looking for a shortcut. Perhaps a little lazily! Thanks for your help anyway.
