### ISSUE TITLE
Roadmap for Neo integration

### ISSUE THREAD

**Issue by bryantAXS** [Firstborn/Craft-Migration-Manager#37]
Hey there, with Neo now available for Craft 3, I wanted to see if you had plans to incorporate here?

thank you!

**Comment by dgrigg** [comment]
@bryantAXS yes. We had support for in in Craft 2 and will be porting that over to the Craft 3 version now that Neo is ready.

**Comment by bryantAXS** [comment]
Fantastic, I'll keep my eyes peeled for updates 👍

**Comment by dgrigg** [comment]
@bryantAXS Neo support has been added in the latest release
