### ISSUE TITLE
Type settings for entry field is incorrectly structured

### ISSUE THREAD

**Issue by my2ter** [Firstborn/Craft-Migration-Manager#40]
Hi,

Should be quite simple to fix.

When you create the sources allowed for an Entry field, the migration's [code](https://github.com/Firstborn/Craft-Migration-Manager/blob/master/src/services/Fields.php#L677)  does:

```$field['typesettings']['sources'] = join($newSources);```

This will generate in your DB:
> {"sources":"section:5section:4"

Craft is expecting an array
> {"sources":["section:4","section:5"]

Your code should be:

`$field['typesettings']['sources'] = in_array('*', $newSources) ? '*' : $newSources;`

Hope it does make sense :)
Cheers

**Comment by my2ter** [comment]
FYI,

When you visit the field settings, it does look like Craft allows you to only select those specific sources, but when you use that field on an entry you can actually select everything.

**Comment by dgrigg** [comment]
@my2ter issue fixed in latest release.
