### ISSUE TITLE
Creating and updating globals fails

### ISSUE THREAD

**Issue by my2ter** [Firstborn/Craft-Migration-Manager#43]
Hi,

The change introduced in https://github.com/Firstborn/Craft-Migration-Manager/blob/v3.0.14/src/services/Globals.php#L92 is actually now preventing Globals to be updated via a migration straight after creating it. It used to work with the previous version https://github.com/Firstborn/Craft-Migration-Manager/blob/v3.0.13/src/services/Globals.php#L97

Here is the scenario:

- Create a global in the CMS with name "Foo" and slug "foo"
- Create a migration
- Update your global in the CMS and change the name to "Bar" but not the slug
- Create a migration
- Run migrations on a brand new install

It will fail because Craft is not capable of finding that Global in https://github.com/craftcms/cms/blob/develop/src/services/Globals.php#L287 and will try to create another Global with the same slug ending with the error "Handle "foo" has already been taken."

While I understand the change you introduced and agree with that logic - and that fact that it might be a Craft issue rather a Firstborn issue - I thought I would flag it with you.

Cheers

**Comment by dgrigg** [comment]
@my2ter if you run the original migration and then the second migration does it run without error? 

The change was introduced because of a Craft issue in finding the correct global to update (if it existed). There is an issue with Craft where database updates that occur within the same transaction don't immediately affect the in memory data model (cached query results). This unfortunately can have a negative impact when running migrations lumped together.

**Comment by my2ter** [comment]
@dgrigg 

Correct, running the migration one at a time wouldn't trigger an error. Unfortunately, I need to be able to run the migration in both cases:

- one at a time
- all migrations in one go

Unless Craft fix that issue, I think your previous implementation was smarter. From the point of view of the migration manager plugin I don't think you should have to "search" for the globals. At the point of creating the migration you already have the **id** so I think this https://github.com/Firstborn/Craft-Migration-Manager/blob/v3.0.13/src/services/Globals.php#L97 was a good idea.

**Comment by dgrigg** [comment]
@my2ter I tested this in Craft 3.1.3 and it's working correctly with consecutive migrations. It looks like P&T fixed the underlying issue in Craft.

**Comment by dgrigg** [comment]
@my2ter  try the latest release 3.0.16
