### ISSUE TITLE
Cant create Migration getVolumeById() must be of the type int

### ISSUE THREAD

**Issue by TobiasDax** [Firstborn/Craft-Migration-Manager#44]
If i try to create my first migration i get the floowing error:
`Argument 1 passed to craft\services\Volumes::getVolumeById() must be of the type int, string given, called in /sites/craft2/vendor/firstborn/migrationmanager/src/services/Fields.php on line 388`

no migration is created. I only tried to create a migration for a singe matrix field

Craft Version: 3.1.3
Amazon S3	1.0.8
Asset Usage	2.0.0-beta.2
Field Manager	2.0.4
Migration Manager	3.0.15
Redactor	2.2.1
Section Field	1.1.0
Super Table	2.1.5.1
Table Maker	2.0.1
Video Embedder	1.1.1

**Comment by damienbuckley** [comment]
Following

**Comment by dgrigg** [comment]
Hi @TobiasDax, does the volume that is being used by the matrix field exist in the destination CMS and does it use the same handle? If not you would need to create a migration for the volume and run it first before the field migration.

**Comment by damienbuckley** [comment]
I’m getting the error when creating the migration to export the fields

**Comment by harispepic** [comment]
same problem here

**Comment by dgrigg** [comment]
@TobiasDax @damienbuckley @harispepic to confirm, you have a Matrix field with a block, the block contains an asset field. Is the asset field restricted to a single asset volume or open to all volumes?

**Comment by harispepic** [comment]
@dgrigg i just figured out the problem by me is coming from the category field.

**Comment by dgrigg** [comment]
@TobiasDax  @damienbuckley any extra details you can provide on the matrix field setup? At this point I can't reproduce the issue you are seeing.

**Comment by dgrigg** [comment]
The issue is related to Craft 3.1 and uids. Working on a fix

**Comment by damienbuckley** [comment]
Happy to pay for this plugin if anything can be done quicker…

**Comment by dgrigg** [comment]
@damienbuckley @TobiasDax   try the latest release 3.0.16
