### ISSUE TITLE
Content Migration Failing on Redactor within Matrix and Sections

### ISSUE THREAD

**Issue by damienbuckley** [Firstborn/Craft-Migration-Manager#46]
Still baulking on Redactor within Matrix fields - seems to import everything else. I get this error:- Status: Internal Server Error

Response: {"error":"An error occurred while executing the \"craft\\contentmigrations\\m190129_122754_migration_brown_bros_fields migration."}

And, getting this when trying to import Sections (after adding the redactor fields to the matrixes manually):-

Response: {"error":"An error occurred while executing the \"craft\\contentmigrations\\m190129_122334_migration_brown_bros_sections migration: Invalid entry type ID: 28"}

Craft v3.1.5, Migration Manager v3.0.16

**Comment by dgrigg** [comment]
Does the section you are migrating have an entry type that does not exist in the destination site or does it appear it just can’t find the right entry type on the destination side?

**Comment by damienbuckley** [comment]
I didn't have the sections. I've added them manually now and migration manager has added the fields etc. Still getting the issue with the field and tag imports though.

Status: Internal Server Error

Response: {"error":"An error occurred while executing the \"craft\\contentmigrations\\m190129_122754_migration_brown_bros_fields migration."}

Status: Internal Server Error

Response: {"error":"An error occurred while executing the \"craft\\contentmigrations\\m190129_122900_migration_brown_bros_tags migration."}

**Comment by dgrigg** [comment]
@damienbuckley should be good now. It wasn't Redactor that was causing the issue, it was the existing Matrix field. Craft 3.1 is a little more particular about how to deal with existing fields than Craft 3.0 was.

**Comment by damienbuckley** [comment]
ok all working now, cheers. Its really critical which order you run things in - I had one site work and another not then realised I'd migrated the tags on one and not the other - I guess the field migration was looking for the tag group…

You should charge for this mate : )

Thanks for fixing it up.

**Comment by dgrigg** [comment]
The order of migrations is sometimes a chicken and egg scenario. I always do small migrations and try to make sure I get any dependencies (ie categories, tag, volumes, tags) first, then fields, then sections.
