### ISSUE TITLE
Version 3.0.16 not updated on packagist

### ISSUE THREAD

**Issue by AlexandreKilian** [Firstborn/Craft-Migration-Manager#47]
On https://packagist.org/packages/firstborn/migrationmanager, there is still version 3.0.15 as the latest, even though a tag for 3.0.16 has been created… this updated is marked as critical, would be nice if it could be updated in packagist so that we can complete the update

**Comment by dgrigg** [comment]
@AlexandreKilian looking into it

**Comment by dgrigg** [comment]
@AlexandreKilian  all good now
