### ISSUE TITLE
Does not respect Lokale setting

### ISSUE THREAD

**Issue by filip-van-hoeckel** [Firstborn/Craft-Migration-Manager#48]
When updating a multilanguage post (using a common ID for both languages) content gets overwritten, instead of updated. We have reproduced this in 3 different instances and all possible orders/configurations.

**Comment by dgrigg** [comment]
Are you seeing different content than what was exported in the migration? Are the wrong locale values being put in the post? Any extra details would be helpful.

**Comment by filip-van-hoeckel** [comment]
Sorry, this is unrelated to Migration Manager.
