### ISSUE TITLE
Asset fields not getting filled in after content migrations

### ISSUE THREAD

**Issue by DimosthenisK** [Firstborn/Craft-Migration-Manager#52]
Hello, All my asset fields seem to be empty after migrating the whole entry. My assets are managed via git and the volumes are local folders. 

It is pretty tedious to reapply all asset fields after every content migration - am I doing something wrong or is this an actual problem with the plugin. 
I am also willing to contribute for a fix if possible. If so, how may I proceed and where should I look inside the file structure?

**Comment by dgrigg** [comment]
Do the assets that are referenced in the asset fields in the migration exist on the server where the migration is executed? The migration manager looks for the asset using the file name and volume. If it can’t find a match it goes to an empty value.

**Comment by DimosthenisK** [comment]
They do exist. If I try to pick the asset after the migration, it exists without me manually uploading it.

**Comment by ilicmarko** [comment]
For some strange reason I can also report this.

Here are my assets:
![image](https://user-images.githubusercontent.com/2827249/53024959-5ccdb280-3460-11e9-8921-7d6859fe9420.png)

Here is a part of my migration:
```json
"blogPostCoverImage":{
    "new1":{
        "type":"27",
        "fields":{
        "photo":[
            {
            "elementType":"craft\\\\elements\\\\Asset",
            "filename":"iStock-638287864.jpg",
            "folder":"posts",
            "source":"awsS3"
            }
        ],
        "photoCreditTo":"Getty Images"
        }
    }
},
```

I do an export and an import, which result my field to be empty.

Here is the whole migration:
```json
{
  "content": {
    "entries": [
      {
        "slug": "temporary-slug-48aada65-3035-4001-a89a",
        "section": "blogPosts",
        "sites": {
          "default": {
            "slug": "temporary-slug-48aada65-3035-4001-a89a",
            "section": "blogPosts",
            "enabled": "1",
            "site": "default",
            "enabledForSite": "1",
            "postDate": {
              "date": "2019-02-19 21:00:00.000000",
              "timezone_type": 3,
              "timezone": "America/Los_Angeles"
            },
            "expiryDate": null,
            "title": "Export test",
            "entryType": "blogPosts",
            "fields": {
              "blogPostTitle": "Export test",
              "blogCategories": [
                {
                  "elementType": "craft\\\\elements\\\\Category",
                  "slug": "my-category",
                  "category": "blogCategories"
                }
              ],
              "blogPostDate": {
                "date": "2019-02-19 21:00:00.000000",
                "timezone_type": 3,
                "timezone": "America/Los_Angeles"
              },
              "blogPostCoverImage": {
                "new1": {
                  "type": "27",
                  "fields": {
                    "photo": [
                      {
                        "elementType": "craft\\\\elements\\\\Asset",
                        "filename": "shopping.jpg",
                        "folder": "posts",
                        "source": "awsS3"
                      }
                    ],
                    "photoCreditTo": "Shopping mall"
                  }
                }
              },
              "blogPostContent": "<p>Hi There</p>",
              "blogPostAuthor": [
                {
                  "elementType": "craft\\\\elements\\\\Entry",
                  "slug": "ilic-marko",
                  "section": "blogAuthor"
                }
              ]
            }
          }
        }
      }
    ]
  }
}
```

**It also doesn't work for `craft\\\\elements\\\\Category` and `craft\\\\elements\\\\Entry`**

---
I have another migration setup for authors and that migration works without a problem. It imports author images, but for some reason for blog posts it doesn't work.

**Comment by DimosthenisK** [comment]
Glad to hear im not alone on this. Let's hope for a fix.

**Comment by ilicmarko** [comment]
Somehow the problem is with the `blogPostContent` and some unescaped HTML breaks the relationship. Still don't know how.

**Comment by dgrigg** [comment]
@voidblaze @ilicmarko can you try adding a Craft::error() in the helper that finds assets during migrations to see what's happening. I have tested with local and S3 folders without issue.  https://github.com/Firstborn/Craft-Migration-Manager/blob/master/src/helpers/MigrationManagerHelper.php#L80 and see

**Comment by dgrigg** [comment]
one thing to make sure, the asset needs to reside in a volume with the same handle name on both sides of the migration.

**Comment by DimosthenisK** [comment]
The handlers are correct and syncronized

**Comment by dgrigg** [comment]
If you add some logging in the getAssetByHandle can you see why it might not be locating the resource

**Comment by ilicmarko** [comment]
Forgot to give an update. It looks like it wasn't the plugin problem... It turned out to be really strange and somehow the HTML that was stored inside the JSON "broke" the relation. Doesn't make a lot of sense but I solved it by encoding the HTML.

**Comment by dgrigg** [comment]
Very odd, is the asset linked in the HTML field or the two are conflicting? How are you encoding the HTML?
