### ISSUE TITLE
Migrations fail with internal server errors about invalid entry type

### ISSUE THREAD

**Issue by hiasl** [Firstborn/Craft-Migration-Manager#57]
My versions: 
+ Craft Version: 3.1.14
+ Migration Manager: 3.0.17
+ Problem is similar to #46 but not the same and not resolved...

Although all fields, assets, globals and categories from my source system are available on the destination system (through migrations), even my simple migrations fail. Addition info: I do not use tags.

When I try to import a rather simple section with only 4 fields on 2 tabs (2 asset selectors, 1 Redactor, 1 text field, all available on the destination system, including the corresponding asset volumes) I get the following error. The section does not yet exist on the destination system.

_Response: {"error":"An error occurred while executing the \"craft\\contentmigrations\\m190227_002140_migration_section_impressionenVideos migration: Invalid entry type ID: 22"}_

I found out, that the entry type ID 22, which the error is referring to, is the next available auto increment value of the entrytypes table, so it seems that the entry type can not be created.

this is the JSON form the migration:
```
private $json = <<<JSON
{"settings":{"dependencies":{"sections":[{"name":"Suchresultat","handle":"search","type":"single","enableVersioning":"1","propagateEntries":"1","sites":{"default":{"site":"default","hasUrls":"1","uriFormat":"suche","enabledByDefault":"1","template":"search/_entry"}},"entrytypes":[{"sectionHandle":"search","hasTitleField":"0","titleLabel":"","titleFormat":"{section.name|raw}","name":"Suchresultat","handle":"search","fieldLayout":{"Basics":["titelImage","contentRichtext"],"SEO":["description","seoImage"]},"requiredFields":[]}]}]},"elements":{"sections":[{"name":"Suchresultat","handle":"search","type":"single","enableVersioning":"1","propagateEntries":"1","sites":{"default":{"site":"default","hasUrls":"1","uriFormat":"suche","enabledByDefault":"1","template":"search/_entry"}},"entrytypes":[{"sectionHandle":"search","hasTitleField":"0","titleLabel":"","titleFormat":"{section.name|raw}","name":"Suchresultat","handle":"search","fieldLayout":{"Basics":["titelImage","contentRichtext"],"SEO":["description","seoImage"]},"requiredFields":[]}]}]}}}
JSON;

```

can you help?
thanks Matthias

**Comment by dgrigg** [comment]
@hiasl I would double check the handles on the fields in the destination system to ensure they match the values on the source side and then check to make sure the entry type ID 22 has the same handle on both sides. It looks like something has gotten out of sync with the handles which would cause issues.

**Comment by hiasl** [comment]
@dgrigg is your answer really meant to be for a migration which brings a NEW section to the destination system? it is not an update to an existing section.

The needed fields exist on the destination system with exactly the correct handles (I just checked again). But since the section which I try to import does not exist, there is also no entry type for it which could have ID 22 (and I also thought that IDs are not important, only handles...)

**Comment by dgrigg** [comment]
@hiasl in the destination site does entry type id 22 relate to something, maybe it is somehow left over. If possible try removing it.

**Comment by hiasl** [comment]
@dgrigg the installation is completely fresh, only one section was migrated before to the destination site. so there is currently only one single entry type belonging to this other section, nothing else  (see screenshot below):
![image](https://user-images.githubusercontent.com/800026/53530599-a1a4b980-3af0-11e9-8d76-1e789253d61c.png)

so as you can see: there it no entry type id 22. 

as mentioned before, the ID referred to in the exception is not an existing ID but is the next available auto increment ID from the entrytype table. I really believe something is going wrong here when creating the new section in the db together with its entry type.

**Comment by hiasl** [comment]
@dgrigg  I think I found the problem:

Migrating Singles does not work, if they do not exist on the destination yet. Structures and Channels work fine.

Overview:

on destination | Singles | Structures | Channels
--|--|--|--
new | **NOK** | ok | ok
update  | ok | ok | ok

**Comment by dgrigg** [comment]
@hiasl try the latest release

**Comment by hiasl** [comment]
@dgrigg not it works like a charm :-)
Thanks a lot!
