### ISSUE TITLE
Content gone after running migration on matrix in matrix field

### ISSUE THREAD

**Issue by roelvanhintum** [Firstborn/Craft-Migration-Manager#58]
Super-table or matrix content is gone after running a migration on a matrix in matrix field.
The following setup is causing the problem for me. I'm using 2 sites in one group for multiple languages.

The content was originally from Craft 2. After the migration of Craft 3.1 and all plugins to the latest version, the content is still there. Migrating the field removes all content (or relations to).

Field is like:
- modules (Matrix)
  - text (MatrixBlock)
    - aside (SuperTable static)
      - asideModule (Matrix)
        - asideText (MatrixBlock)
          - asideTitle (PlainText)
          - body (Redactor)
        - asideOther (MatrixBlock)
        - etc
  - other (MatrixBlock)
  - etc

I'm using:
- Craft CMS 3.1.15
- Migration Manager 3.0.19
- Super Table 2.1.13.1

**Comment by dgrigg** [comment]
Does the migration file have the content for the asideModule or is it empty?

**Comment by roelvanhintum** [comment]
The migration does not contain content. I'm just migrating fields.

**Comment by dgrigg** [comment]
Does the field structure migrate properly?

**Comment by roelvanhintum** [comment]
Yes, the structure looks fine. I can also create new content which does save. Running another migration on the field, without any changes to the structure, the content is removed again.

**Comment by dgrigg** [comment]
@roelvanhintum try the latest release
