### ISSUE TITLE
Packagist is missing v3.0.20

### ISSUE THREAD

**Issue by roelvanhintum** [Firstborn/Craft-Migration-Manager#59]
I think packagist isn't connecting correctly to your github account. Releases on github should automatically publish to packagist.

**Comment by dgrigg** [comment]
@roelvanhintum try now, we have been having issues with our Packagist account.

**Comment by roelvanhintum** [comment]
@dgrigg I recently had the same thing. Disconnect and reconnect github to packagist solved it for me.
