### ISSUE TITLE
getFieldGroupByName ignoring DB_TABLE_PREFIX

### ISSUE THREAD

**Issue by jerome2710** [Firstborn/Craft-Migration-Manager#6]
When importing fields within a group, the following query in this function fails: [getFieldGroupByName](https://github.com/Firstborn/Craft-Migration-Manager/blob/master/src/services/Fields.php#L139).

This might be because the plugin ignores the DB_TABLE_PREFIX environment-setting?

The error:
```json
{"error":"An error occurred while executing the \"craft\\contentmigrations\\m180502_135655_migration_XXX migration: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pj_XXX.fieldgroups' doesn't exist The SQL being executed was: SELECT `id`, `name` FROM `fieldgroups`WHERE `name`='Common' ORDER BY `name` DESC LIMIT 1"}
```

**Comment by jerome2710** [comment]
Please check [this pull-request](https://github.com/Firstborn/Craft-Migration-Manager/pull/7) which seems to sort this issue for me.

**Comment by fb-derrick-grigg** [comment]
@jerome2710 fixed, thanks for the PR, nice catch
