### ISSUE TITLE
Throws non-descriptive error message

### ISSUE THREAD

**Issue by filip-van-hoeckel** [Firstborn/Craft-Migration-Manager#60]
When trying to import a file the following error is thrown and import fails: 

`{"error":"An error occurred while executing the \"craft\\contentmigrations\\m190226_171245_migration_entry_names_omitted for privacy_purposes migration: Trying to get property 'id' of non-object"}`

**Comment by dgrigg** [comment]
@filip-van-hoeckel do you have any additional details to go along with that? Are other migrations working? Which file/line number?

**Comment by filip-van-hoeckel** [comment]
from the log:
`Next craft\errors\MigrationException: An error occurred while executing the "craft\contentmigrations\m190304_171439_migration_section_entrancecrewmember migration: Trying to get property 'id' of non-object in /home/u26020p20101/domains/domainemea.com/craft/vendor/craftcms/cms/src/db/MigrationManager.php:260
Stack trace:
#0 /home/u26020p20101/domains/domainemea.com/craft/vendor/firstborn/migrationmanager/src/services/Migrations.php(327): craft\db\MigrationManager->migrateUp(Object(craft\contentmigrations\m190304_171439_migration_section_entrancecrewmember))
#1 /home/u26020p20101/domains/domainemea.com/craft/vendor/firstborn/migrationmanager/src/controllers/RunController.php(109): firstborn\migrationmanager\services\Migrations->runMigrations(Array)
#2 [internal function]: firstborn\migrationmanager\controllers\RunController->actionMigrations()
#3 /home/u26020p20101/domains/domainemea.com/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#4 /home/u26020p20101/domains/domainemea.com/craft/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#5 /home/u26020p20101/domains/domainemea.com/craft/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('migrations', Array)
#6 /home/u26020p20101/domains/domainemea.com/craft/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrations', Array)
#7 /home/u26020p20101/domains/domainemea.com/craft/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('migrationmanage...', Array)
#8 /home/u26020p20101/domains/domainemea.com/craft/vendor/craftcms/cms/src/web/Application.php(561): craft\web\Application->runAction('migrationmanage...', Array)
#9 /home/u26020p20101/domains/domainemea.com/craft/vendor/craftcms/cms/src/web/Application.php(281): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#10 /home/u26020p20101/domains/domainemea.com/craft/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#11 /home/u26020p20101/domains/domainemea.com/public_html/index.php(21): yii\base\Application->run()
#12 {main}`

**Comment by dgrigg** [comment]
@filip-van-hoeckel what are you attempting to migrate?

**Comment by filip-van-hoeckel** [comment]
A section at first, then the contents of the section.

**Comment by dgrigg** [comment]
Are there any errors higher up in the error log that point to a specific service in the migration manager?

**Comment by filip-van-hoeckel** [comment]
Something like this you mean? 
`2019-03-04 17:13:30 [-][2][-][error][craft\errors\MigrationException] yii\base\ErrorException: Trying to get property 'id' of non-object in /home/u26020p20101/domains/domainemea.com/craft/vendor/firstborn/migrationmanager/src/services/Sections.php:189
Stack trace:
#0 /home/u26020p20101/domains/domainemea.com/craft/vendor/craftcms/cms/src/web/ErrorHandler.php(76): yii\base\ErrorHandler->handleError(8, 'Trying to get p...', '/home/u26020p20...', 189)
#1 /home/u26020p20101/domains/domainemea.com/craft/vendor/firstborn/migrationmanager/src/services/Sections.php(189): craft\web\ErrorHandler->handleError(8, 'Trying to get p...', '/home/u26020p20...', 189, Array)
#2 /home/u26020p20101/domains/domainemea.com/craft/vendor/firstborn/migrationmanager/src/services/Sections.php(121): firstborn\migrationmanager\services\Sections->createModel(Array)
#3 /home/u26020p20101/domains/domainemea.com/craft/vendor/firstborn/migrationmanager/src/services/BaseMigration.php(147): firstborn\migrationmanager\services\Sections->importItem(Array)
#4 /home/u26020p20101/domains/domainemea.com/craft/vendor/firstborn/migrationmanager/src/services/Migrations.php(250): firstborn\migrationmanager\services\BaseMigration->import(Array)
#5 /home/u26020p20101/domains/domainemea.com/craft/migrations/m190304_171439_migration_section_entrancecrewmember.php(36): firstborn\migrationmanager\services\Migrations->import(Array)
#6 /home/u26020p20101/domains/domainemea.com/craft/vendor/craftcms/cms/src/db/Migration.php(56): craft\contentmigrations\m190304_171439_migration_section_entrancecrewmember->safeUp()
#7 /home/u26020p20101/domains/domainemea.com/craft/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#8 /home/u26020p20101/domains/domainemea.com/craft/vendor/firstborn/migrationmanager/src/services/Migrations.php(327): craft\db\MigrationManager->migrateUp(Object(craft\contentmigrations\m190304_171439_migration_section_entrancecrewmember))
#9 /home/u26020p20101/domains/domainemea.com/craft/vendor/firstborn/migrationmanager/src/controllers/RunController.php(109): firstborn\migrationmanager\services\Migrations->runMigrations(Array)
#10 [internal function]: firstborn\migrationmanager\controllers\RunController->actionMigrations()
#11 /home/u26020p20101/domains/domainemea.com/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /home/u26020p20101/domains/domainemea.com/craft/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#13 /home/u26020p20101/domains/domainemea.com/craft/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('migrations', Array)
#14 /home/u26020p20101/domains/domainemea.com/craft/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrations', Array)
#15 /home/u26020p20101/domains/domainemea.com/craft/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('migrationmanage...', Array)
#16 /home/u26020p20101/domains/domainemea.com/craft/vendor/craftcms/cms/src/web/Application.php(561): craft\web\Application->runAction('migrationmanage...', Array)
#17 /home/u26020p20101/domains/domainemea.com/craft/vendor/craftcms/cms/src/web/Application.php(281): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#18 /home/u26020p20101/domains/domainemea.com/craft/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#19 /home/u26020p20101/domains/domainemea.com/public_html/index.php(21): yii\base\Application->run()
#20 {main}`

**Comment by dgrigg** [comment]
https://github.com/Firstborn/Craft-Migration-Manager/blob/master/src/services/Sections.php#L189

It looks like you are migrating a section for a site that doesn't exist on the destination side. Check the sites on the source and destination installations to make sure they are up to date.

I'll add some extra error messaging around that to make it more obvious.

**Comment by filip-van-hoeckel** [comment]
Hmm, so I should build the section first then migrate? Maybe I have the wrong assumption, but isn't this product supposed to migrate structure and content from one site to the other?

**Comment by dgrigg** [comment]
You need to migrate the site(s) first. Sections are related to sites so when the section migration runs it is looking for a site that doesn't exist on the destination side.

**Comment by dgrigg** [comment]
Everything will migrate structure and content, it just depends on making sure all the pieces have been migrated. With the various dependencies between data types it's impossible to create a single migration that captures them all. Typically you would just migrate sites near the beginning of your setup since those likely won't change over time.

**Comment by dgrigg** [comment]
@filip-van-hoeckel I added some addition logging that might be helpful

**Comment by filip-van-hoeckel** [comment]
> You need to migrate the site(s) first.

And where exactly is this documented?!

**Comment by dgrigg** [comment]
from the readme.md, 
"It is important to remember to create Migrations in an order that is consistent with manually creating fields, sections etc. Fields must exist before they can be added to Sections. Categories must exist before they can be used by Fields, etc. When creating migrations keep that in mind, break your migrations into smaller steps to prevent issues instead of one large migration."

**Comment by filip-van-hoeckel** [comment]
I'd like to suggest the addition of Sites to the documentation as well. I also like to suggest descriptive error messaging, or even: asking the user whether structures found in the file should be created or overwritten.
