### ISSUE TITLE
Run migrations from command-line

### ISSUE THREAD

**Issue by AlexandreKilian** [Firstborn/Craft-Migration-Manager#62]
Hello,

is there currently a way to run migrations from the command line? would be really helpful for CI/CD pipelines…

**Comment by dgrigg** [comment]
Unfortunately not for the Craft 2 version. Craft 3 version has this feature.

**Comment by AlexandreKilian** [comment]
@dgrigg oh, the regular `./craft migrate/up` work? Maybe it just failed for some other reason back when I last tried that
